"""added image column

Revision ID: b57b9d2012d7
Revises: 1855bcc82df6
Create Date: 2023-12-21 15:27:46.374737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57b9d2012d7'
down_revision = '1855bcc82df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_mimetype', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image_mimetype')
        batch_op.drop_column('image_filename')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
